LedController: led_controller/include/cgi.h File Reference
cgi.h File Reference
#include <stdio.h>
#include "lwip/apps/httpd.h"
Functions
const char * cgi_onboard_led_handler (int iIndex, int iNumParams, char *pcParam[], char *pcValue[])
CGI onboard LED handler.
const char * cgi_led_handler (int iIndex, int iNumParams, char *pcParam[], char *pcValue[])
CGI LED handler.
const char * cgi_led_mode_handler (int iIndex, int iNumParams, char *pcParam[], char *pcValue[])
CGI LED mode handler.
const char * cgi_led_color_handler (int iIndex, int iNumParams, char *pcParam[], char *pcValue[])
CGI LED color handler.
const char * cgi_led_brightness_handler (int iIndex, int iNumParams, char *pcParam[], char *pcValue[])
CGI LED strip brightness handler.
const char * cgi_favicon_handler (int iIndex, int iNumParams, char *pcParam[], char *pcValue[])
CGI favicon handler.
const char * cgi_m_icon_handler (int iIndex, int iNumParams, char *pcParam[], char *pcValue[])
CGI m icon handler.
const char * cgi_manifest_handler (int iIndex, int iNumParams, char *pcParam[], char *pcValue[])
CGI manifest handler.
const char * cgi_data_handler (int iIndex, int iNumParams, char *pcParam[], char *pcValue[])
CGI data handler.
const char * cgi_timestamp_handler (int iIndex, int iNumParams, char *pcParam[], char *pcValue[])
CGI timestamp handler.
void cgi_init ()
Initialize CGI handlers.
Variables
static const tCGI cgi_handlers []
CGI handlers.
Function Documentation
cgi_data_handler()
const char * cgi_data_handler (int iIndex, int iNumParams, char * pcParam[], char * pcValue[])
CGI data handler.
Function handles CGI requests for the data.
Parameters
iIndex index of the CGI handler
iNumParams number of parameters
pcParam array of parameters
pcValue array of values
Returns
: redirect URL
Definition at line 266 of file cgi.c.
{
    printf("Handling data request\n");
    return "/data.shtml";
}
cgi_favicon_handler()
const char * cgi_favicon_handler (int iIndex, int iNumParams, char * pcParam[], char * pcValue[])
CGI favicon handler.
Function handles CGI requests for the favicon.
Parameters
iIndex index of the CGI handler
iNumParams number of parameters
pcParam array of parameters
pcValue array of values
Returns
: redirect URL
Definition at line 248 of file cgi.c.
{
    printf("Handling favicon request\n");
    return "/favicon.ico";
}
cgi_init()
void cgi_init ()
Initialize CGI handlers.
Function initializes the CGI handling and respective handlers.
Definition at line 278 of file cgi.c.
{
    http_set_cgi_handlers(cgi_handlers, LWIP_ARRAYSIZE(cgi_handlers));
}
References cgi_handlers.
Referenced by init().
cgi_led_brightness_handler()
const char * cgi_led_brightness_handler (int iIndex, int iNumParams, char * pcParam[], char * pcValue[])
CGI LED strip brightness handler.
Function handles CGI requests for the LED strip brightness change.
Parameters
iIndex index of the CGI handler
iNumParams number of parameters
pcParam array of parameters
pcValue array of values
Returns
: redirect URL
Definition at line 217 of file cgi.c.
{
    printf("Handling brightness request\n");
    for (int i = 0; i < iNumParams; ++i)
    {
        int brightness = atoi(pcParam[i]);
        if (brightness < 0 || brightness > 100)
            printf("Invalid brightness value\n");
        else
        {
            printf("Setting brightness to %d\n", brightness);
            if (brightness == 0)
                brightness = 0;
            else if (brightness == 100)
                brightness = 255;
            else
            {
                brightness = (int)(brightness * 255.0 / 100.0) + 1;
                if (brightness > 255)
                    brightness = 255;
                else if (brightness < 0)
                    brightness = 0;
            }
            light_state.brightness = brightness;
        }
        if (light_state.light_mode == MODE_STATIC)
            set_light_color(light_state.color);
    }
    return "/index.html";
}
References light_state_t::brightness, light_state_t::color, light_state_t::light_mode, light_state, MODE_STATIC, and set_light_color().
cgi_led_color_handler()
const char * cgi_led_color_handler (int iIndex, int iNumParams, char * pcParam[], char * pcValue[])
CGI LED color handler.
Function handles CGI requests for the LED strip color.
Parameters
iIndex index of the CGI handler
iNumParams number of parameters
pcParam array of parameters
pcValue array of values
Returns
: redirect URL
Definition at line 131 of file cgi.c.
{
    printf("Handling color request\n");
    for (int i = 0; i < iNumParams; ++i)
    {
        if (!strcmp(pcParam[i], "red"))
        {
            printf("Setting red mode\n");
            light_state.state = true;
            set_light_color(COLOR_RED);
            break;
        }
        else if (!strcmp(pcParam[i], "green"))
        {
            printf("Setting green mode\n");
            light_state.state = true;
            set_light_color(COLOR_GREEN);
            break;
        }
        else if (!strcmp(pcParam[i], "blue"))
        {
            printf("Setting blue mode\n");
            light_state.state = true;
            set_light_color(COLOR_BLUE);
            break;
        }
        else if (!strcmp(pcParam[i], "cyan"))
        {
            printf("Setting cyan mode\n");
            light_state.state = true;
            set_light_color(COLOR_CYAN);
            break;
        }
        else if (!strcmp(pcParam[i], "yellow"))
        {
            printf("Setting yellow mode\n");
            light_state.state = true;
            set_light_color(COLOR_YELLOW);
            break;
        }
        else if (!strcmp(pcParam[i], "magenta"))
        {
            printf("Setting magenta mode\n");
            light_state.state = true;
            set_light_color(COLOR_MAGENTA);
            break;
        }
        else if (!strcmp(pcParam[i], "purple"))
        {
            printf("Setting purple mode\n");
            light_state.state = true;
            set_light_color(COLOR_PURPLE);
            break;
        }
        else if (!strcmp(pcParam[i], "pink"))
        {
            printf("Setting pink mode\n");
            light_state.state = true;
            set_light_color(COLOR_PINK);
            break;
        }
        else if (!strcmp(pcParam[i], "orange"))
        {
            printf("Setting orange mode\n");
            light_state.state = true;
            set_light_color(COLOR_ORANGE);
            break;
        }
        else if (!strcmp(pcParam[i], "turquoise"))
        {
            printf("Setting turquoise mode\n");
            light_state.state = true;
            set_light_color(COLOR_TURQUOISE);
            break;
        }
        else if (!strcmp(pcParam[i], "white"))
        {
            printf("Setting white mode\n");
            light_state.state = true;
            set_light_color(COLOR_WHITE);
            break;
        }
    }
    return "/index.html";
}
References COLOR_BLUE, COLOR_CYAN, COLOR_GREEN, COLOR_MAGENTA, COLOR_ORANGE, COLOR_PINK, COLOR_PURPLE, COLOR_RED, COLOR_TURQUOISE, COLOR_WHITE, COLOR_YELLOW, light_state, set_light_color(), and light_state_t::state.
cgi_led_handler()
const char * cgi_led_handler (int iIndex, int iNumParams, char * pcParam[], char * pcValue[])
CGI LED handler.
Function handles CGI requests for the LED strip.
Parameters
iIndex index of the CGI handler
iNumParams number of parameters
pcParam array of parameters
pcValue array of values
Returns
: redirect URL
Definition at line 39 of file cgi.c.
{
    printf("Handling LED request\n");
    for (int i = 0; i < iNumParams; ++i)
    {
        if (!strcmp(pcParam[i], "toggle"))
        {
            printf("Toggling LED strip\n");
            toggle_light_state();
            break;
        }
        else if (!strcmp(pcParam[i], "on"))
        {
            printf("Turning LED strip on\n");
            light_state.state = true;
            break;
        }
        else if (!strcmp(pcParam[i], "off"))
        {
            printf("Turning LED strip off\n");
            light_state.state = false;
            break;
        }
    }
    return "/index.html";
}
References light_state, light_state_t::state, and toggle_light_state().
cgi_led_mode_handler()
const char * cgi_led_mode_handler (int iIndex, int iNumParams, char * pcParam[], char * pcValue[])
CGI LED mode handler.
Function handles CGI requests for the LED strip mode.
Parameters
iIndex index of the CGI handler
iNumParams number of parameters
pcParam array of parameters
pcValue array of values
Returns
: redirect URL
Definition at line 66 of file cgi.c.
{
    printf("Handling mode request\n");
    for (int i = 0; i < iNumParams; ++i)
    {
        if (!strcmp(pcParam[i], "rainbow-wheel"))
        {
            printf("Setting rainbow wheel mode\n");
            light_state.state = true;
            set_light_mode(MODE_RAINBOW_WHEEL);
            break;
        }
        else if (!strcmp(pcParam[i], "rainbow-cycle"))
        {
            printf("Setting rainbow cycle mode\n");
            light_state.state = true;
            set_light_mode(MODE_RAINBOW_CYCLE);
            break;
        }
        else if (!strcmp(pcParam[i], "static"))
        {
            printf("Setting static mode\n");
            light_state.state = true;
            set_light_mode(MODE_STATIC);
            break;
        }
        else if (!strcmp(pcParam[i], "breathing"))
        {
            printf("Setting breathing mode\n");
            light_state.state = true;
            set_light_mode(MODE_BREATHING);
            break;
        }
        else if (!strcmp(pcParam[i], "flashing"))
        {
            printf("Setting flashing mode\n");
            light_state.state = true;
            set_light_mode(MODE_FLASHING);
            break;
        }
        else if (!strcmp(pcParam[i], "loading"))
        {
            printf("Setting loading mode\n");
            light_state.state = true;
            set_light_mode(MODE_LOADING);
            break;
        }
        else if (!strcmp(pcParam[i], "wave"))
        {
            printf("Setting wave mode\n");
            light_state.state = true;
            set_light_mode(MODE_WAVE);
            break;
        }
        else if (!strcmp(pcParam[i], "fade"))
        {
            printf("Setting fade mode\n");
            light_state.state = true;
            set_light_mode(MODE_FADE);
            break;
        }
    }
    return "/index.html";
}
References light_state, MODE_BREATHING, MODE_FADE, MODE_FLASHING, MODE_LOADING, MODE_RAINBOW_CYCLE, MODE_RAINBOW_WHEEL, MODE_STATIC, MODE_WAVE, set_light_mode(), and light_state_t::state.
cgi_m_icon_handler()
const char * cgi_m_icon_handler (int iIndex, int iNumParams, char * pcParam[], char * pcValue[])
CGI m icon handler.
Function handles CGI requests for the m icon.
Parameters
iIndex index of the CGI handler
iNumParams number of parameters
pcParam array of parameters
pcValue array of values
Returns
: redirect URL
Definition at line 254 of file cgi.c.
{
    printf("Handling m.png\n");
    return "/m.png";
}
cgi_manifest_handler()
const char * cgi_manifest_handler (int iIndex, int iNumParams, char * pcParam[], char * pcValue[])
CGI manifest handler.
Function handles CGI requests for the manifest.
Parameters
iIndex index of the CGI handler
iNumParams number of parameters
pcParam array of parameters
pcValue array of values
Returns
: redirect URL
Definition at line 260 of file cgi.c.
{
    printf("Handling manifest request\n");
    return "/manifest.json";
}
cgi_onboard_led_handler()
const char * cgi_onboard_led_handler (int iIndex, int iNumParams, char * pcParam[], char * pcValue[])
CGI onboard LED handler.
Function handles CGI requests for the onboard LED.
Parameters
iIndex index of the CGI handler
iNumParams number of parameters
pcParam array of parameters
pcValue array of values
Returns
: redirect URL
Definition at line 12 of file cgi.c.
{
    printf("Handling onboard LED request\n");
    for (int i = 0; i < iNumParams; ++i)
    {
        if (!strcmp(pcParam[i], "toggle"))
        {
            printf("Toggling onboard LED\n");
            cyw43_arch_gpio_put(CYW43_WL_GPIO_LED_PIN, !cyw43_arch_gpio_get(CYW43_WL_GPIO_LED_PIN));
            break;
        }
        else if (!strcmp(pcParam[i], "on"))
        {
            printf("Turning onboard LED on\n");
            cyw43_arch_gpio_put(CYW43_WL_GPIO_LED_PIN, 1);
            break;
        }
        else if (!strcmp(pcParam[i], "off"))
        {
            printf("Turning onboard LED off\n");
            cyw43_arch_gpio_put(CYW43_WL_GPIO_LED_PIN, 0);
            break;
        }
    }
    return "/index.html";
}
cgi_timestamp_handler()
const char * cgi_timestamp_handler (int iIndex, int iNumParams, char * pcParam[], char * pcValue[])
CGI timestamp handler.
Function handles CGI requests for the timestamp.
Parameters
iIndex index of the CGI handler
iNumParams number of parameters
pcParam array of parameters
pcValue array of values
Returns
: redirect URL
Definition at line 272 of file cgi.c.
{
    printf("Handling start timestamp request\n");
    return "/timestamp.shtml";
}
Variable Documentation
cgi_handlers
const tCGI cgi_handlers[] static
Initial value:
=
{
    { "/onboard_led", cgi_onboard_led_handler },
    { "/led", cgi_led_handler },
    { "/mode", cgi_led_mode_handler },
    { "/color", cgi_led_color_handler },
    { "/brightness", cgi_led_brightness_handler },
    { "/favicon.ico", cgi_favicon_handler },
    { "/m.png", cgi_m_icon_handler },
    { "/manifest.json", cgi_manifest_handler },
    { "/data.shtml", cgi_data_handler },
    { "/timestamp.shtml", cgi_timestamp_handler },
    { NULL, NULL }
}
CGI handlers.
Array of CGI handlers with endpoint and handler function.
Definition at line 120 of file cgi.h.
{
    { "/onboard_led", cgi_onboard_led_handler },
    { "/led", cgi_led_handler },
    { "/mode", cgi_led_mode_handler },
    { "/color", cgi_led_color_handler },
    { "/brightness", cgi_led_brightness_handler },
    { "/favicon.ico", cgi_favicon_handler },
    { "/m.png", cgi_m_icon_handler },
    { "/manifest.json", cgi_manifest_handler },
    { "/data.shtml", cgi_data_handler },
    { "/timestamp.shtml", cgi_timestamp_handler },
    { NULL, NULL }
};
Referenced by cgi_init().