LedController: led_controller/src/hsv.c File Reference
hsv.c File Reference
#include "hsv.h"
#include "urgb.h"
Functions
uint32_t hsv_to_rgb (uint16_t h, uint8_t s, uint8_t v)
Convert HSV to RGB.
Function Documentation
hsv_to_rgb()
uint32_t hsv_to_rgb (uint16_t h, uint8_t s, uint8_t v)
Convert HSV to RGB.
Parameters
h hue
s saturation
v value
Returns
: RGB 32-bit color
Definition at line 5 of file hsv.c.
{
    float hf = h / 60.0f;
    float sf = s / 255.0f;
    float vf = v / 255.0f;
    int i = (int)hf % 6;
    float f = hf - (int)hf;
    uint8_t p = (uint8_t)(vf * (1.0f - sf) * 255);
    uint8_t q = (uint8_t)(vf * (1.0f - sf * f) * 255);
    uint8_t t = (uint8_t)(vf * (1.0f - sf * (1.0f - f)) * 255);
    uint8_t vi = (uint8_t)(vf * 255);
    uint8_t r, g, b;
    switch (i) {
        case 0:
            r = vi;
            g = t;
            b = p;
            break;
        case 1:
            r = q;
            g = vi;
            b = p;
            break;
        case 2:
            r = p;
            g = vi;
            b = t;
            break;
        case 3:
            r = p;
            g = q;
            b = vi;
            break;
        case 4:
            r = t;
            g = p;
            b = vi;
            break;
        case 5:
            r = vi;
            g = p;
            b = q;
            break;
    }
    return URGB(r, g, b);
}
References URGB.
Referenced by apply_rainbow_cycle_effect(), apply_rainbow_wheel_effect(), and set_rainbow_spectrum().