LedController: led_controller/src/led_controller.c File Reference
led_controller.c File Reference
#include "led_controller.h"
#include <stdio.h>
#include <stdlib.h>
#include "urgb.h"
#include "hsv.h"
#include "ws2812b.h"
#include "light_state.h"
#include "wifi_credentials.h"
#include "generated/ws2812.pio.h"
#include "lwipopts.h"
#include "lwip/apps/httpd.h"
#include "ssi.h"
#include "cgi.h"
#include "ntp.h"
Functions
void connect_to_wifi ()
Connect to WiFi.
void gpio_button_irq_handler (uint gpio, uint32_t events)
GPIO button interrupt handler.
enum init_result_t init ()
Init.
void run_loop ()
Run loop.
Variables
volatile bool light_state_toggle_request = false
volatile bool light_mode_toggle_request = false
volatile bool stop_flag = false
volatile uint64_t last_press_time = 0
Function Documentation
connect_to_wifi()
void connect_to_wifi ()
Connect to WiFi.
Function connects to WiFi using the SSID and password defined in the wifi_credentials.h file.
Definition at line 24 of file led_controller.c.
{
    BLINK_CODE_WIFI_CONNECTING;
    printf("Connecting to Wi-Fi...\n");
    while (cyw43_arch_wifi_connect_timeout_ms(WIFI_SSID, WIFI_PASSWORD, CYW43_AUTH_WPA2_AES_PSK, 10000) != 0)
        printf("Attempting to connect...\n");
    printf("Connected!\n");
    extern cyw43_t cyw43_state;
    uint32_t ip_addr = cyw43_state.netif[CYW43_ITF_STA].ip_addr.addr;
    printf("IP Address: %lu.%lu.%lu.%lu\n", ip_addr & 0xFF, (ip_addr >> 8) & 0xFF, (ip_addr >> 16) & 0xFF, ip_addr >> 24);
    BLINK_CODE_WIFI_CONNECTED;
}
References BLINK_CODE_WIFI_CONNECTED, BLINK_CODE_WIFI_CONNECTING, WIFI_PASSWORD, and WIFI_SSID.
Referenced by init(), and main().
gpio_button_irq_handler()
void gpio_button_irq_handler (uint gpio, uint32_t events)
GPIO button interrupt handler.
Function handles button interrupts setting proper flags.
Definition at line 37 of file led_controller.c.
{
    uint64_t current_time = time_us_64();
    if (current_time - last_press_time >= DEBOUNCE_TIME_US)
    {
        last_press_time = current_time;
        switch (gpio)
        {
        case LIGHT_TOGGLE_PIN:
            light_state_toggle_request = true;
            break;
        case MODE_BUTTON_PIN:
            light_mode_toggle_request = true;
            if (!light_state.state)
                light_state_toggle_request = true;
            break;
        case STOP_BUTTON_PIN:
            stop_flag = true;
            break;
        default:
            break;
        }
    }
}
References DEBOUNCE_TIME_US, last_press_time, light_mode_toggle_request, light_state, light_state_toggle_request, LIGHT_TOGGLE_PIN, MODE_BUTTON_PIN, light_state_t::state, STOP_BUTTON_PIN, and stop_flag.
Referenced by init().
init()
enum init_result_t init ()
Init.
Function initializes the LED controller.
Returns
: initialization result
Definition at line 62 of file led_controller.c.
{
    if (!stdio_init_all())
    {
        printf("Stdio init failed");
        return STDIO_INIT_FAILURE;
    }
    // GPIO setup - LED
    gpio_init(CYW43_WL_GPIO_LED_PIN);
    gpio_set_dir(CYW43_WL_GPIO_LED_PIN, GPIO_OUT);
    gpio_put(CYW43_WL_GPIO_LED_PIN, 0);
    // GPIO setup - buttons
    gpio_init(LIGHT_TOGGLE_PIN);
    gpio_set_dir(LIGHT_TOGGLE_PIN, GPIO_IN);
    gpio_pull_up(LIGHT_TOGGLE_PIN);
    gpio_init(MODE_BUTTON_PIN);
    gpio_set_dir(MODE_BUTTON_PIN, GPIO_IN);
    gpio_pull_up(MODE_BUTTON_PIN);
    gpio_init(STOP_BUTTON_PIN);
    gpio_set_dir(STOP_BUTTON_PIN, GPIO_IN);
    gpio_pull_up(STOP_BUTTON_PIN);
    // GPIO setup - interrupts
    gpio_set_irq_enabled_with_callback(LIGHT_TOGGLE_PIN, GPIO_IRQ_EDGE_FALL, true, &gpio_button_irq_handler);
    gpio_set_irq_enabled_with_callback(MODE_BUTTON_PIN, GPIO_IRQ_EDGE_FALL, true, &gpio_button_irq_handler);
    gpio_set_irq_enabled_with_callback(STOP_BUTTON_PIN, GPIO_IRQ_EDGE_FALL, true, &gpio_button_irq_handler);
    // Wi-Fi setup
    if (cyw43_arch_init())
    {
        printf("Wi-Fi init failed");
        return WIFI_INIT_FAILURE;
    }
    cyw43_wifi_pm(&cyw43_state, cyw43_pm_value(CYW43_NO_POWERSAVE_MODE, 20, 1, 1, 1));
    cyw43_arch_enable_sta_mode();
    connect_to_wifi();
    httpd_init();
    ssi_init();
    cgi_init();
    ntp_update_time();
    BLINK_CODE_NETWORK_INIT_SUCCESS;
    // PIO setup - WS2812B
    PIO pio = pio0;
    int sm = 0;
    uint offset = pio_add_program(pio, &ws2812_program);
    ws2812_program_init(pio, sm, offset, WS2812_PIN, 800000, IS_RGBW);
    printf("WS2812 LED Control, using pin %d\n", WS2812_PIN);
    BLINK_CODE_INIT_SUCCESS;
    return INIT_SUCCESS;
}
References BLINK_CODE_INIT_SUCCESS, BLINK_CODE_NETWORK_INIT_SUCCESS, cgi_init(), connect_to_wifi(), gpio_button_irq_handler(), INIT_SUCCESS, IS_RGBW, LIGHT_TOGGLE_PIN, MODE_BUTTON_PIN, ntp_update_time(), ssi_init(), STDIO_INIT_FAILURE, STOP_BUTTON_PIN, WIFI_INIT_FAILURE, WS2812_PIN, ws2812_program, and ws2812_program_init().
Referenced by main().
run_loop()
void run_loop ()
Run loop.
Function runs the main loop of the LED controller.
Definition at line 119 of file led_controller.c.
{
    uint16_t base_hue = 0;
    uint8_t speed_factor_wheel = 4;
    uint8_t speed_factor_cycle = 1;
    uint8_t speed_factor_breathing = 3;
    uint8_t density_factor = 3;
    uint8_t breathing_brightness = 15;
    bool breathing_up = true;
    while (true)
    {
        if (light_mode_toggle_request)
        {
            toggle_light_mode();
            light_mode_toggle_request = false;
        }
        if (light_state_toggle_request)
        {
            toggle_light_state();
            light_state_toggle_request = false;
        }
        if (stop_flag)
        {
            turn_off_all(NUM_PIXELS);
            break;
        }
        switch (light_state.light_mode)
        {
        case MODE_RAINBOW_WHEEL:
            if (light_state.state)
                apply_rainbow_wheel_effect(NUM_PIXELS, &base_hue, &speed_factor_wheel, &density_factor, &light_state.brightness);
            break;
        case MODE_RAINBOW_CYCLE:
            if (light_state.state)
                apply_rainbow_cycle_effect(NUM_PIXELS, &base_hue, &speed_factor_cycle, &light_state.brightness);
            break;
        case MODE_BREATHING:
            if (light_state.state)
            {
                uint32_t current_color = get_current_color();
                apply_breathing_effect(NUM_PIXELS, &speed_factor_breathing, &current_color, &light_state.brightness, &breathing_brightness, &breathing_up);
            }
            break;
        case MODE_FLASHING:
            if (light_state.state)
            {
                uint32_t current_color = get_current_color();
                apply_flashing_effect(NUM_PIXELS, &current_color);
            }
            break;
        // [ ] Implement the rest of dynamic modes
        default:
            break;
        }
        sleep_ms(40);
    }
}
References apply_breathing_effect(), apply_flashing_effect(), apply_rainbow_cycle_effect(), apply_rainbow_wheel_effect(), light_state_t::brightness, get_current_color(), light_state_t::light_mode, light_mode_toggle_request, light_state, light_state_toggle_request, MODE_BREATHING, MODE_FLASHING, MODE_RAINBOW_CYCLE, MODE_RAINBOW_WHEEL, NUM_PIXELS, light_state_t::state, stop_flag, toggle_light_mode(), toggle_light_state(), and turn_off_all().
Referenced by main().
Variable Documentation
last_press_time
volatile uint64_t last_press_time = 0
Definition at line 22 of file led_controller.c.
Referenced by gpio_button_irq_handler().
light_mode_toggle_request
volatile bool light_mode_toggle_request = false
Definition at line 20 of file led_controller.c.
Referenced by gpio_button_irq_handler(), and run_loop().
light_state_toggle_request
volatile bool light_state_toggle_request = false
Definition at line 19 of file led_controller.c.
Referenced by gpio_button_irq_handler(), and run_loop().
stop_flag
volatile bool stop_flag = false
Definition at line 21 of file led_controller.c.
Referenced by gpio_button_irq_handler(), main(), and run_loop().