LedController: led_controller/src/light_state.c File Reference
light_state.c File Reference
#include "light_state.h"
#include <stdint.h>
#include "urgb.h"
#include "ws2812b.h"
Functions
void toggle_light_state ()
Toggle light state.
void toggle_light_mode ()
Toggle light mode.
void toggle_light_color ()
Toggle light color.
void set_light_mode (enum light_modes mode)
Set light mode.
void set_light_color (enum light_colors color)
Set light color.
uint32_t get_current_color ()
Get current color.
Variables
volatile struct light_state_t light_state = {true, 128, MODE_RAINBOW_WHEEL, COLOR_BLUE}
Light state.
Function Documentation
get_current_color()
uint32_t get_current_color ()
Get current color.
Function gets the current color.
Returns
current color in RGB format
Definition at line 116 of file light_state.c.
{
    switch (light_state.color)
    {
    case COLOR_RED:
        return get_red(light_state.brightness);
    case COLOR_GREEN:
        return get_green(light_state.brightness);
    case COLOR_BLUE:
        return get_blue(light_state.brightness);
    case COLOR_WHITE:
        return get_white(light_state.brightness);
    case COLOR_PURPLE:
        return get_purple(light_state.brightness);
    case COLOR_YELLOW:
        return get_yellow(light_state.brightness);
    case COLOR_CYAN:
        return get_cyan(light_state.brightness);
    case COLOR_ORANGE:
        return get_orange(light_state.brightness);
    case COLOR_PINK:
        return get_pink(light_state.brightness);
    case COLOR_TURQUOISE:
        return get_turquoise(light_state.brightness);
    case COLOR_MAGENTA:
        return get_magenta(light_state.brightness);
    default:
        return 0;
    }
}
References light_state_t::brightness, light_state_t::color, COLOR_BLUE, COLOR_CYAN, COLOR_GREEN, COLOR_MAGENTA, COLOR_ORANGE, COLOR_PINK, COLOR_PURPLE, COLOR_RED, COLOR_TURQUOISE, COLOR_WHITE, COLOR_YELLOW, get_blue(), get_cyan(), get_green(), get_magenta(), get_orange(), get_pink(), get_purple(), get_red(), get_turquoise(), get_white(), get_yellow(), and light_state.
Referenced by run_loop().
set_light_color()
void set_light_color (enum light_colors color)
Set light color.
Function sets the light mode to the specified color.
Parameters
color color
Definition at line 68 of file light_state.c.
{
    light_state.color = color;
    if (!light_state.state || light_state.brightness == 0)
        return;
    if (light_state.light_mode == MODE_STATIC)
    {
        switch (color)
        {
        case COLOR_RED:
            set_all_red(NUM_PIXELS, light_state.brightness);
            break;
        case COLOR_GREEN:
            set_all_green(NUM_PIXELS, light_state.brightness);
            break;
        case COLOR_BLUE:
            set_all_blue(NUM_PIXELS, light_state.brightness);
            break;
        case COLOR_WHITE:
            set_all_white(NUM_PIXELS, light_state.brightness);
            break;
        case COLOR_PURPLE:
            set_all_purple(NUM_PIXELS, light_state.brightness);
            break;
        case COLOR_YELLOW:
            set_all_yellow(NUM_PIXELS, light_state.brightness);
            break;
        case COLOR_CYAN:
            set_all_cyan(NUM_PIXELS, light_state.brightness);
            break;
        case COLOR_ORANGE:
            set_all_orange(NUM_PIXELS, light_state.brightness);
            break;
        case COLOR_PINK:
            set_all_pink(NUM_PIXELS, light_state.brightness);
            break;
        case COLOR_TURQUOISE:
            set_all_turquoise(NUM_PIXELS, light_state.brightness);
            break;
        case COLOR_MAGENTA:
            set_all_magenta(NUM_PIXELS, light_state.brightness);
            break;
        default:
            break;
        }
    }
}
References light_state_t::brightness, light_state_t::color, COLOR_BLUE, COLOR_CYAN, COLOR_GREEN, COLOR_MAGENTA, COLOR_ORANGE, COLOR_PINK, COLOR_PURPLE, COLOR_RED, COLOR_TURQUOISE, COLOR_WHITE, COLOR_YELLOW, light_state_t::light_mode, light_state, MODE_STATIC, NUM_PIXELS, set_all_blue(), set_all_cyan(), set_all_green(), set_all_magenta(), set_all_orange(), set_all_pink(), set_all_purple(), set_all_red(), set_all_turquoise(), set_all_white(), set_all_yellow(), and light_state_t::state.
Referenced by cgi_led_brightness_handler(), cgi_led_color_handler(), set_light_mode(), and toggle_light_color().
set_light_mode()
void set_light_mode (enum light_modes mode)
Set light mode.
Function sets the light mode to the specified mode.
Parameters
mode mode
Definition at line 31 of file light_state.c.
{
    light_state.light_mode = mode;
    if (!light_state.state || light_state.brightness == 0)
        return;
    switch (mode)
    {
    case MODE_RAINBOW_WHEEL:
        printf("Setting rainbow wheel mode\n");
        break;
    case MODE_RAINBOW_CYCLE:
        printf("Setting rainbow cycle mode\n");
        break;
    case MODE_STATIC:
        printf("Setting static mode\n");
        set_light_color(light_state.color);
        break;
    case MODE_BREATHING:
        printf("Setting breathing mode\n");
        break;
    case MODE_FLASHING:
        printf("Setting flashing mode\n");
        break;
    case MODE_LOADING:
        printf("Setting loading mode\n");
        break;
    case MODE_WAVE:
        printf("Setting wave mode\n");
        break;
    case MODE_FADE:
        printf("Setting fade mode\n");
        break;
    default:
        break;
    }
}
References light_state_t::brightness, light_state_t::color, light_state_t::light_mode, light_state, MODE_BREATHING, MODE_FADE, MODE_FLASHING, MODE_LOADING, MODE_RAINBOW_CYCLE, MODE_RAINBOW_WHEEL, MODE_STATIC, MODE_WAVE, set_light_color(), and light_state_t::state.
Referenced by cgi_led_mode_handler(), toggle_light_mode(), and toggle_light_state().
toggle_light_color()
void toggle_light_color ()
Toggle light color.
Function toggles the light color iterating through the light colors.
Definition at line 25 of file light_state.c.
{
    light_state.color = (light_state.color + 1) % NUM_LIGHT_COLORS;
    set_light_color(light_state.color);
}
References light_state_t::color, light_state, NUM_LIGHT_COLORS, and set_light_color().
toggle_light_mode()
void toggle_light_mode ()
Toggle light mode.
Function toggles the light mode iterating through the light modes.
Definition at line 19 of file light_state.c.
{
    light_state.light_mode = (light_state.light_mode + 1) % NUM_LIGHT_MODES;
    set_light_mode(light_state.light_mode);
}
References light_state_t::light_mode, light_state, NUM_LIGHT_MODES, and set_light_mode().
Referenced by run_loop().
toggle_light_state()
void toggle_light_state ()
Toggle light state.
Function toggles on/off the light state.
Definition at line 10 of file light_state.c.
{
    light_state.state = !light_state.state;
    if (!light_state.state || light_state.brightness == 0)
        turn_off_all(NUM_PIXELS);
    else
        set_light_mode(light_state.light_mode);
}
References light_state_t::brightness, light_state_t::light_mode, light_state, NUM_PIXELS, set_light_mode(), light_state_t::state, and turn_off_all().
Referenced by cgi_led_handler(), led_blink(), and run_loop().
Variable Documentation
light_state
volatile struct light_state_t light_state = {true, 128, MODE_RAINBOW_WHEEL, COLOR_BLUE}
Light state.
External, not optimized variable for the light state.
Definition at line 8 of file light_state.c.
{true, 128, MODE_RAINBOW_WHEEL, COLOR_BLUE};
Referenced by cgi_led_brightness_handler(), cgi_led_color_handler(), cgi_led_handler(), cgi_led_mode_handler(), get_current_color(), gpio_button_irq_handler(), run_loop(), set_light_color(), set_light_mode(), ssi_handler(), toggle_light_color(), toggle_light_mode(), and toggle_light_state().