LedController: led_controller/src/ntp.c File Reference
ntp.c File Reference
#include "ntp.h"
#include <string.h>
#include <time.h>
#include "pico/stdlib.h"
#include "pico/cyw43_arch.h"
#include "lwip/dns.h"
#include "lwip/pbuf.h"
#include "lwip/udp.h"
Functions
static void ntp_result (NTP_T *state, int status, time_t *result)
static void ntp_request (NTP_T *state)
static int64_t ntp_failed_handler (alarm_id_t id, void *user_data)
static void ntp_dns_found (const char *hostname, const ip_addr_t *ipaddr, void *arg)
static void ntp_recv (void *arg, struct udp_pcb *pcb, struct pbuf *p, const ip_addr_t *addr, u16_t port)
static NTP_T * ntp_init (void)
void ntp_deinit (void)
void ntp_update_time (void)
Variables
volatile struct tm * utc = NULL
Function Documentation
ntp_deinit()
void ntp_deinit (void)
Definition at line 111 of file ntp.c.
{
    if (utc)
    {
        free((void*)utc);
        utc = NULL;
    }
}
References utc.
Referenced by main().
ntp_dns_found()
static void ntp_dns_found (const char * hostname, const ip_addr_t * ipaddr, void * arg) static
Definition at line 53 of file ntp.c.
{
    NTP_T *state = (NTP_T*)arg;
    if (ipaddr)
    {
        state->ntp_server_address = *ipaddr;
        printf("NTP address %s\n", ipaddr_ntoa(ipaddr));
        ntp_request(state);
    }
    else
    {
        printf("NTP DNS request failed\n");
        ntp_result(state, -1, NULL);
    }
}
References ntp_request(), ntp_result(), and NTP_T_::ntp_server_address.
Referenced by ntp_update_time().
ntp_failed_handler()
static int64_t ntp_failed_handler (alarm_id_t id, void * user_data) static
Definition at line 45 of file ntp.c.
{
    NTP_T* state = (NTP_T*)user_data;
    printf("NTP request failed\n");
    ntp_result(state, -1, NULL);
    return 0;
}
References ntp_result().
Referenced by ntp_update_time().
ntp_init()
static NTP_T * ntp_init (void) static
Definition at line 92 of file ntp.c.
{
    NTP_T *state = (NTP_T*)calloc(1, sizeof(NTP_T));
    if (!state)
    {
        printf("Failed to allocate state\n");
        return NULL;
    }
    state->ntp_pcb = udp_new_ip_type(IPADDR_TYPE_ANY);
    if (!state->ntp_pcb)
    {
        printf("Failed to create PCB\n");
        free(state);
        return NULL;
    }
    udp_recv(state->ntp_pcb, ntp_recv, state);
    return state;
}
References NTP_T_::ntp_pcb, and ntp_recv().
Referenced by ntp_update_time().
ntp_recv()
static void ntp_recv (void * arg, struct udp_pcb * pcb, struct pbuf * p, const ip_addr_t * addr, u16_t port) static
Definition at line 69 of file ntp.c.
{
    NTP_T *state = (NTP_T*)arg;
    uint8_t mode = pbuf_get_at(p, 0) & 0x7;
    uint8_t stratum = pbuf_get_at(p, 1);
    if (ip_addr_cmp(addr, &state->ntp_server_address) && port == NTP_PORT && p->tot_len == NTP_MSG_LEN &&mode == 0x4 && stratum != 0)
    {
        uint8_t seconds_buf[4] = {0};
        pbuf_copy_partial(p, seconds_buf, sizeof(seconds_buf), 40);
        uint32_t seconds_since_1900 = seconds_buf[0] << 24 | seconds_buf[1] << 16 | seconds_buf[2] << 8 | seconds_buf[3];
        uint32_t seconds_since_1970 = seconds_since_1900 - NTP_DELTA;
        time_t epoch = seconds_since_1970;
        ntp_result(state, 0, &epoch);
    }
    else
    {
        printf("Invalid NTP response\n");
        ntp_result(state, -1, NULL);
    }
    pbuf_free(p);
}
References NTP_DELTA, NTP_MSG_LEN, NTP_PORT, ntp_result(), and NTP_T_::ntp_server_address.
Referenced by ntp_init().
ntp_request()
static void ntp_request (NTP_T * state) static
Definition at line 33 of file ntp.c.
{
    cyw43_arch_lwip_begin();
    struct pbuf *p = pbuf_alloc(PBUF_TRANSPORT, NTP_MSG_LEN, PBUF_RAM);
    uint8_t *req = (uint8_t *) p->payload;
    memset(req, 0, NTP_MSG_LEN);
    req[0] = 0x1b;
    udp_sendto(state->ntp_pcb, p, &state->ntp_server_address, NTP_PORT);
    pbuf_free(p);
    cyw43_arch_lwip_end();
}
References NTP_MSG_LEN, NTP_T_::ntp_pcb, NTP_PORT, and NTP_T_::ntp_server_address.
Referenced by ntp_dns_found(), and ntp_update_time().
ntp_result()
static void ntp_result (NTP_T * state, int status, time_t * result) static
Definition at line 15 of file ntp.c.
{
    if (status == 0 && result)
    {
        // *result += TIMEZONE_OFFSET;
        utc = gmtime(result);
        printf("Got NTP response: %02d/%02d/%04d %02d:%02d:%02d\n", utc->tm_mday, utc->tm_mon + 1, utc->tm_year + 1900, utc->tm_hour, utc->tm_min, utc->tm_sec);
    }
    if (state->ntp_resend_alarm > 0)
    {
        cancel_alarm(state->ntp_resend_alarm);
        state->ntp_resend_alarm = 0;
    }
    state->ntp_test_time = make_timeout_time_ms(NTP_TEST_TIME);
    state->dns_request_sent = false;
}
References NTP_T_::dns_request_sent, NTP_T_::ntp_resend_alarm, NTP_TEST_TIME, NTP_T_::ntp_test_time, and utc.
Referenced by ntp_dns_found(), ntp_failed_handler(), ntp_recv(), and ntp_update_time().
ntp_update_time()
void ntp_update_time (void)
Definition at line 120 of file ntp.c.
{
    NTP_T *state = ntp_init();
    if (!state)
        return;
    if (absolute_time_diff_us(get_absolute_time(), state->ntp_test_time) < 0 && !state->dns_request_sent)
    {
        state->ntp_resend_alarm = add_alarm_in_ms(NTP_RESEND_TIME, ntp_failed_handler, state, true);
        cyw43_arch_lwip_begin();
        int err = dns_gethostbyname(NTP_SERVER, &state->ntp_server_address, ntp_dns_found, state);
        cyw43_arch_lwip_end();
        state->dns_request_sent = true;
        if (err == ERR_OK)
            ntp_request(state);
        else if (err != ERR_INPROGRESS)
        {
            printf("DNS request failed\n");
            ntp_result(state, -1, NULL);
        }
    }
    free(state);
}
References NTP_T_::dns_request_sent, ntp_dns_found(), ntp_failed_handler(), ntp_init(), ntp_request(), NTP_T_::ntp_resend_alarm, NTP_RESEND_TIME, ntp_result(), NTP_SERVER, NTP_T_::ntp_server_address, and NTP_T_::ntp_test_time.
Referenced by init().
Variable Documentation
utc
volatile struct tm* utc = NULL
Definition at line 13 of file ntp.c.
Referenced by ntp_deinit(), ntp_result(), and ssi_handler().