LedController: led_controller/include/ntp.h File Reference
ntp.h File Reference
#include <string.h>
#include <time.h>
#include "pico/stdlib.h"
#include "pico/cyw43_arch.h"
#include "lwip/dns.h"
#include "lwip/pbuf.h"
#include "lwip/udp.h"
Data Structures
struct NTP_T_
NTP struct.
Macros
#define NTP_SERVER "pool.ntp.org"
#define NTP_MSG_LEN 48
#define NTP_PORT 123
#define NTP_DELTA 2208988800
#define NTP_TEST_TIME (30 * 1000)
#define NTP_RESEND_TIME (10 * 1000)
Typedefs
typedef struct NTP_T_ NTP_T
NTP struct.
Functions
static void ntp_result (NTP_T *state, int status, time_t *result)
NTP result.
static int64_t ntp_failed_handler (alarm_id_t id, void *user_data)
NTP failed handler.
static void ntp_request (NTP_T *state)
NTP request.
static void ntp_dns_found (const char *hostname, const ip_addr_t *ipaddr, void *arg)
NTP DNS found.
static void ntp_recv (void *arg, struct udp_pcb *pcb, struct pbuf *p, const ip_addr_t *addr, u16_t port)
NTP recv.
static NTP_T * ntp_init (void)
NTP init.
void ntp_deinit (void)
NTP deinit.
void ntp_update_time (void)
NTP update time.
Variables
volatile struct tm * utc
UTC time struct.
volatile struct tm * current_utc
UTC time struct.
Macro Definition Documentation
NTP_DELTA
#define NTP_DELTA 2208988800
Definition at line 17 of file ntp.h.
Referenced by ntp_recv().
NTP_MSG_LEN
#define NTP_MSG_LEN 48
Definition at line 15 of file ntp.h.
Referenced by ntp_recv(), and ntp_request().
NTP_PORT
#define NTP_PORT 123
Definition at line 16 of file ntp.h.
Referenced by ntp_recv(), and ntp_request().
NTP_RESEND_TIME
#define NTP_RESEND_TIME (10 * 1000)
Definition at line 19 of file ntp.h.
Referenced by ntp_update_time().
NTP_SERVER
#define NTP_SERVER "pool.ntp.org"
Definition at line 14 of file ntp.h.
Referenced by ntp_update_time().
NTP_TEST_TIME
#define NTP_TEST_TIME (30 * 1000)
Definition at line 18 of file ntp.h.
Referenced by ntp_result().
Typedef Documentation
NTP_T
typedef struct NTP_T_ NTP_T
NTP struct.
Struct for the NTP state.
Function Documentation
ntp_deinit()
void ntp_deinit (void)
NTP deinit.
Function de-initializes the NTP.
Definition at line 114 of file ntp.c.
{
    if (utc)
    {
        free((void*)utc);
        utc = NULL;
    }
}
References utc.
Referenced by main().
ntp_dns_found()
static void ntp_dns_found (const char * hostname, const ip_addr_t * ipaddr, void * arg) static
NTP DNS found.
Function handles the NTP DNS found.
Parameters
hostname hostname
ipaddr IP address
arg argument
ntp_failed_handler()
static int64_t ntp_failed_handler (alarm_id_t id, void * user_data) static
NTP failed handler.
NTP DNS found.
Function handles the NTP failed handler.
Parameters
id alarm ID
user_data user data
Returns
: time
Function handles the NTP DNS found.
Parameters
hostname hostname
ipaddr IP address
arg argument
ntp_init()
static NTP_T * ntp_init (void) static
NTP init.
Function initializes the NTP.
Returns
: NTP state
ntp_recv()
static void ntp_recv (void * arg, struct udp_pcb * pcb, struct pbuf * p, const ip_addr_t * addr, u16_t port) static
NTP recv.
Function receives the NTP response.
Parameters
arg argument
pcb UDP PCB
p pbuf
addr IP address
port port
ntp_request()
static void ntp_request (NTP_T * state) static
NTP request.
Function sends the NTP request.
Parameters
state NTP state
ntp_result()
static void ntp_result (NTP_T * state, int status, time_t * result) static
NTP result.
Function handles the NTP result.
Parameters
state NTP state
status status
result result
ntp_update_time()
void ntp_update_time (void)
NTP update time.
Function updates the NTP time.
Definition at line 123 of file ntp.c.
{
    NTP_T *state = ntp_init();
    if (!state)
        return;
    if (absolute_time_diff_us(get_absolute_time(), state->ntp_test_time) < 0 && !state->dns_request_sent)
    {
        state->ntp_resend_alarm = add_alarm_in_ms(NTP_RESEND_TIME, ntp_failed_handler, state, true);
        cyw43_arch_lwip_begin();
        int err = dns_gethostbyname(NTP_SERVER, &state->ntp_server_address, ntp_dns_found, state);
        cyw43_arch_lwip_end();
        state->dns_request_sent = true;
        if (err == ERR_OK)
            ntp_request(state);
        else if (err != ERR_INPROGRESS)
        {
            printf("DNS request failed\n");
            ntp_result(state, -1, NULL);
        }
    }
    free(state);
}
References NTP_T_::dns_request_sent, ntp_dns_found(), ntp_failed_handler(), ntp_init(), ntp_request(), NTP_T_::ntp_resend_alarm, NTP_RESEND_TIME, ntp_result(), NTP_SERVER, NTP_T_::ntp_server_address, and NTP_T_::ntp_test_time.
Referenced by init().
Variable Documentation
current_utc
volatile struct tm* current_utc extern
UTC time struct.
Struct for the last checked UTC time.
Definition at line 14 of file ntp.c.
Referenced by ntp_result().
utc
volatile struct tm* utc extern
UTC time struct.
Struct for the UTC time of program start.
Definition at line 13 of file ntp.c.
Referenced by ntp_deinit(), ntp_result(), and ssi_handler().