LedController: led_controller/src/ws2812b.c File Reference
ws2812b.c File Reference
#include "ws2812b.h"
#include <stdlib.h>
#include <time.h>
#include "urgb.h"
#include "hsv.h"
#include "generated/ws2812.pio.h"
Functions
static void put_pixel (uint32_t pixel_grb)
void set_all_leds (uint32_t color, uint len)
Set all leds to the same color.
void turn_off_all (uint len)
Turn off all leds.
uint32_t get_red (uint8_t brightness)
Get red color.
uint32_t get_green (uint8_t brightness)
Get green color.
uint32_t get_blue (uint8_t brightness)
Get blue color.
uint32_t get_white (uint8_t brightness)
Get white color.
uint32_t get_purple (uint8_t brightness)
Get purple color.
uint32_t get_yellow (uint8_t brightness)
Get yellow color.
uint32_t get_cyan (uint8_t brightness)
Get cyan color.
uint32_t get_orange (uint8_t brightness)
Get orange color.
uint32_t get_pink (uint8_t brightness)
Get pink color.
uint32_t get_turquoise (uint8_t brightness)
Get turquoise color.
uint32_t get_magenta (uint8_t brightness)
Get magenta color.
void set_all_red (uint len, uint8_t brightness)
Set all leds to red.
void set_all_green (uint len, uint8_t brightness)
Set all leds to green.
void set_all_blue (uint len, uint8_t brightness)
Set all leds to blue.
void set_all_white (uint len, uint8_t brightness)
Set all leds to white.
void set_all_purple (uint len, uint8_t brightness)
Set all leds purple.
void set_all_yellow (uint len, uint8_t brightness)
Set all leds yellow.
void set_all_cyan (uint len, uint8_t brightness)
Set all leds cyan.
void set_all_orange (uint len, uint8_t brightness)
Set all leds orange.
void set_all_pink (uint len, uint8_t brightness)
Set all leds pink.
void set_all_turquoise (uint len, uint8_t brightness)
Set all leds turquoise.
void set_all_magenta (uint len, uint8_t brightness)
Set all leds magenta.
void set_rainbow_spectrum (uint len)
Set all leds to rainbow spectrum.
void apply_rainbow_wheel_effect (uint len, uint16_t *base_hue, uint8_t *speed_factor, uint8_t *density_factor, volatile uint8_t *brightness)
Apply rainbow wheel effect.
void apply_rainbow_cycle_effect (uint len, uint16_t *hue, uint8_t *speed_factor, volatile uint8_t *brightness)
Apply rainbow cycle effect.
void apply_breathing_effect (uint len, uint8_t *speed_factor, uint32_t *color, volatile uint8_t *base_brightness, uint8_t *brightness, bool *breathing_up)
Apply breathing effect.
void apply_flashing_effect (uint len, uint32_t *color)
Apply flashing effect.
Function Documentation
apply_breathing_effect()
void apply_breathing_effect (uint len, uint8_t * speed_factor, uint32_t * color, volatile uint8_t * base_brightness, uint8_t * brightness, bool * breathing_up)
Apply breathing effect.
Parameters
len number of leds
speed_factor speed factor
color color
base_brightness base brightness
brightness brightness
breathing_up breathing up
Definition at line 184 of file ws2812b.c.
{
    uint8_t min_brightness = 15;
    uint8_t max_brightness = *base_brightness;
    if (max_brightness < min_brightness)
        max_brightness = min_brightness;
    for (uint i = 0; i < len; ++i)
    {
        uint8_t r = URGB_R(*color);
        uint8_t g = URGB_G(*color);
        uint8_t b = URGB_B(*color);
        uint32_t color = URGB(r * *brightness / 255, g * *brightness / 255, b * *brightness / 255);
        put_pixel(color);
    }
    if (*brightness >= max_brightness)
    {
        *breathing_up = false;
        *brightness = max_brightness;
    }
    else if (*brightness <= min_brightness)
    {
        *breathing_up = true;
        *brightness = min_brightness;
    }
    if (*breathing_up)
        *brightness += *speed_factor;
    else
        *brightness -= *speed_factor;
}
References put_pixel(), URGB, URGB_B, URGB_G, and URGB_R.
Referenced by run_loop().
apply_flashing_effect()
void apply_flashing_effect (uint len, uint32_t * color)
Apply flashing effect.
Parameters
len number of leds
led_values led values
color color
Definition at line 214 of file ws2812b.c.
{
    srand(time(NULL));
    int num_led_flash = 10;
    int *random_indices = (int *)malloc(num_led_flash * sizeof(int));
    for (int i = 0; i < num_led_flash; ++i)
        random_indices[i] = rand() % len;
    int leds_handled = 0;
    while (leds_handled < len)
    {
        int i = 0;
        if (random_indices[i] == leds_handled)
        {
            uint32_t new_color;
            if (!color)
                new_color = URGB(rand() % 256, rand() % 256, rand() % 256);
            else
            {
                uint8_t r = URGB_R(*color);
                uint8_t g = URGB_G(*color);
                uint8_t b = URGB_B(*color);
                new_color = URGB(r, g, b);
            }
            put_pixel(new_color);
            i++;
            if (i >= num_led_flash)
                break;
        }
        else
            put_pixel(0);
        leds_handled++;
    }
}
References put_pixel(), URGB, URGB_B, URGB_G, and URGB_R.
Referenced by run_loop().
apply_rainbow_cycle_effect()
void apply_rainbow_cycle_effect (uint len, uint16_t * hue, uint8_t * speed_factor, volatile uint8_t * brightness)
Apply rainbow cycle effect.
Parameters
len number of leds
hue hue
speed_factor speed factor
brightness brightness
Definition at line 174 of file ws2812b.c.
{
    for (uint i = 0; i < len; ++i)
    {
        uint32_t color = hsv_to_rgb(*hue, 255, *brightness);
        put_pixel(color);
    }
    *hue += *speed_factor;
}
References hsv_to_rgb(), and put_pixel().
Referenced by run_loop().
apply_rainbow_wheel_effect()
void apply_rainbow_wheel_effect (uint len, uint16_t * base_hue, uint8_t * speed_factor, uint8_t * density_factor, volatile uint8_t * brightness)
Apply rainbow wheel effect.
Parameters
len number of leds
base_hue base hue
speed_factor speed factor
density_factor density factor
brightness brightness
Definition at line 160 of file ws2812b.c.
{
    for (uint i = 0; i < len; ++i)
    {
        uint16_t hue = (*base_hue + i * 360 / len * *density_factor) % 360;
        uint32_t color = hsv_to_rgb(hue, 255, *brightness);
        put_pixel(color);
        hue++;
    }
    *speed_factor = rand() % 3 + 6; // 6, 7, 8
    *base_hue += *speed_factor;
    *base_hue %= 360;
}
References hsv_to_rgb(), and put_pixel().
Referenced by run_loop().
get_blue()
uint32_t get_blue (uint8_t brightness)
Get blue color.
Parameters
brightness brightness
Returns
blue color in RGB format
Definition at line 40 of file ws2812b.c.
{
    return URGB(0, 0, brightness);
}
References URGB.
Referenced by get_current_color().
get_cyan()
uint32_t get_cyan (uint8_t brightness)
Get cyan color.
Parameters
brightness brightness
Returns
cyan color in RGB format
Definition at line 60 of file ws2812b.c.
{
    return URGB(0, brightness, brightness);
}
References URGB.
Referenced by get_current_color().
get_green()
uint32_t get_green (uint8_t brightness)
Get green color.
Parameters
brightness brightness
Returns
green color in RGB format
Definition at line 35 of file ws2812b.c.
{
    return URGB(0, brightness, 0);
}
References URGB.
Referenced by get_current_color().
get_magenta()
uint32_t get_magenta (uint8_t brightness)
Get magenta color.
Parameters
brightness brightness
Returns
magenta color in RGB format
Definition at line 80 of file ws2812b.c.
{
    return URGB(brightness, 0, brightness);
}
References URGB.
Referenced by get_current_color().
get_orange()
uint32_t get_orange (uint8_t brightness)
Get orange color.
Parameters
brightness brightness
Returns
orange color in RGB format
Definition at line 65 of file ws2812b.c.
{
    return URGB(brightness, brightness / 3, 0);
}
References URGB.
Referenced by get_current_color().
get_pink()
uint32_t get_pink (uint8_t brightness)
Get pink color.
Parameters
brightness brightness
Returns
pink color in RGB format
Definition at line 70 of file ws2812b.c.
{
    return URGB(brightness, brightness / 3, brightness / 3);
}
References URGB.
Referenced by get_current_color().
get_purple()
uint32_t get_purple (uint8_t brightness)
Get purple color.
Parameters
brightness brightness
Returns
purple color in RGB format
Definition at line 50 of file ws2812b.c.
{
    return URGB(brightness * 3 / 4, 0, brightness);
}
References URGB.
Referenced by get_current_color().
get_red()
uint32_t get_red (uint8_t brightness)
Get red color.
Parameters
brightness brightness
Returns
red color in RGB format
Definition at line 30 of file ws2812b.c.
{
    return URGB(brightness, 0, 0);
}
References URGB.
Referenced by get_current_color().
get_turquoise()
uint32_t get_turquoise (uint8_t brightness)
Get turquoise color.
Parameters
brightness brightness
Returns
turquoise color in RGB format
Definition at line 75 of file ws2812b.c.
{
    return URGB(brightness / 3, brightness * 2 / 3, brightness);
}
References URGB.
Referenced by get_current_color().
get_white()
uint32_t get_white (uint8_t brightness)
Get white color.
Parameters
brightness brightness
Returns
white color in RGB format
Definition at line 45 of file ws2812b.c.
{
    return URGB(brightness, brightness, brightness);
}
References URGB.
Referenced by get_current_color().
get_yellow()
uint32_t get_yellow (uint8_t brightness)
Get yellow color.
Parameters
brightness brightness
Returns
yellow color in RGB format
Definition at line 55 of file ws2812b.c.
{
    return URGB(brightness, brightness, 0);
}
References URGB.
Referenced by get_current_color().
put_pixel()
static void put_pixel (uint32_t pixel_grb) inline static
Definition at line 10 of file ws2812b.c.
{
    pio_sm_put_blocking(pio0, 0, pixel_grb << 8u);
}
Referenced by apply_breathing_effect(), apply_flashing_effect(), apply_rainbow_cycle_effect(), apply_rainbow_wheel_effect(), set_all_leds(), and set_rainbow_spectrum().
set_all_blue()
void set_all_blue (uint len, uint8_t brightness)
Set all leds to blue.
Parameters
len number of leds
brightness brightness
Definition at line 97 of file ws2812b.c.
{
    uint32_t blue = URGB(0, 0, brightness);
    set_all_leds(blue, len);
}
References set_all_leds(), and URGB.
Referenced by set_light_color().
set_all_cyan()
void set_all_cyan (uint len, uint8_t brightness)
Set all leds cyan.
Parameters
len number of leds
brightness brightness
Definition at line 121 of file ws2812b.c.
{
    uint32_t cyan = URGB(0, brightness, brightness);
    set_all_leds(cyan, len);
}
References set_all_leds(), and URGB.
Referenced by set_light_color().
set_all_green()
void set_all_green (uint len, uint8_t brightness)
Set all leds to green.
Parameters
len number of leds
brightness brightness
Definition at line 91 of file ws2812b.c.
{
    uint32_t green = URGB(0, brightness, 0);
    set_all_leds(green, len);
}
References set_all_leds(), and URGB.
Referenced by set_light_color().
set_all_leds()
void set_all_leds (uint32_t color, uint len)
Set all leds to the same color.
Parameters
color color in RGB format
len number of leds
Definition at line 15 of file ws2812b.c.
{
    for (uint i = 0; i < len; ++i)
    {
        put_pixel(color);
    }
}
References put_pixel().
Referenced by set_all_blue(), set_all_cyan(), set_all_green(), set_all_magenta(), set_all_orange(), set_all_pink(), set_all_purple(), set_all_red(), set_all_turquoise(), set_all_white(), set_all_yellow(), and turn_off_all().
set_all_magenta()
void set_all_magenta (uint len, uint8_t brightness)
Set all leds magenta.
Parameters
len number of leds
brightness brightness
Definition at line 145 of file ws2812b.c.
{
    uint32_t magenta = URGB(brightness, 0, brightness);
    set_all_leds(magenta, len);
}
References set_all_leds(), and URGB.
Referenced by set_light_color().
set_all_orange()
void set_all_orange (uint len, uint8_t brightness)
Set all leds orange.
Parameters
len number of leds
brightness brightness
Definition at line 127 of file ws2812b.c.
{
    uint32_t orange = URGB(brightness, brightness / 3, 0);
    set_all_leds(orange, len);
}
References set_all_leds(), and URGB.
Referenced by set_light_color().
set_all_pink()
void set_all_pink (uint len, uint8_t brightness)
Set all leds pink.
Parameters
len number of leds
brightness brightness
Definition at line 133 of file ws2812b.c.
{
    uint32_t pink = URGB(brightness, brightness / 3, brightness / 3);
    set_all_leds(pink, len);
}
References set_all_leds(), and URGB.
Referenced by set_light_color().
set_all_purple()
void set_all_purple (uint len, uint8_t brightness)
Set all leds purple.
Parameters
len number of leds
brightness brightness
Definition at line 109 of file ws2812b.c.
{
    uint32_t purple = URGB(brightness * 3 / 4, 0, brightness);
    set_all_leds(purple, len);
}
References set_all_leds(), and URGB.
Referenced by set_light_color().
set_all_red()
void set_all_red (uint len, uint8_t brightness)
Set all leds to red.
Parameters
len number of leds
brightness brightness
Definition at line 85 of file ws2812b.c.
{
    uint32_t red = URGB(brightness, 0, 0);
    set_all_leds(red, len);
}
References set_all_leds(), and URGB.
Referenced by set_light_color().
set_all_turquoise()
void set_all_turquoise (uint len, uint8_t brightness)
Set all leds turquoise.
Parameters
len number of leds
brightness brightness
Definition at line 139 of file ws2812b.c.
{
    uint32_t turquoise = URGB(brightness / 3, brightness * 2 / 3, brightness);
    set_all_leds(turquoise, len);
}
References set_all_leds(), and URGB.
Referenced by set_light_color().
set_all_white()
void set_all_white (uint len, uint8_t brightness)
Set all leds to white.
Parameters
len number of leds
brightness brightness
Definition at line 103 of file ws2812b.c.
{
    uint32_t white = URGB(brightness, brightness, brightness);
    set_all_leds(white, len);
}
References set_all_leds(), and URGB.
Referenced by set_light_color().
set_all_yellow()
void set_all_yellow (uint len, uint8_t brightness)
Set all leds yellow.
Parameters
len number of leds
brightness brightness
Definition at line 115 of file ws2812b.c.
{
    uint32_t yellow = URGB(brightness, brightness, 0);
    set_all_leds(yellow, len);
}
References set_all_leds(), and URGB.
Referenced by set_light_color().
set_rainbow_spectrum()
void set_rainbow_spectrum (uint len)
Set all leds to rainbow spectrum.
Parameters
len number of leds
Definition at line 151 of file ws2812b.c.
{
    for (uint i = 0; i < len; ++i)
    {
        uint32_t color = hsv_to_rgb(i * 360 / len, 255, 255);
        put_pixel(color);
    }
}
References hsv_to_rgb(), and put_pixel().
turn_off_all()
void turn_off_all (uint len)
Turn off all leds.
Parameters
len number of leds
Definition at line 23 of file ws2812b.c.
{
    uint32_t off = URGB(0, 0, 0);
    set_all_leds(off, len);
}
References set_all_leds(), and URGB.
Referenced by run_loop(), and toggle_light_state().